//user
export const LOGIN_USER = 'LOGIN_USER'

//hospital
export const GET_HOSPITAL_LIST = 'GET_HOSPITAL_LIST'
export const CHANGE_CUR_HOSPITAL = 'CHANGE_CUR_HOSPITAL'
export const GET_SELECT_DEPARTMENT_LIST = 'GET_SELECT_DEPARTMENT_LIST'
export const CHANGE_CUR_DEPARTMENT = 'CHANGE_CUR_DEPARTMENT'
